# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_personalinformation_predentalweekendsignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=140, null=True, verbose_name='First Name')),
                ('lastName', models.CharField(blank=True, max_length=140, null=True, verbose_name='Last Name')),
                ('contactNumber', models.CharField(blank=True, max_length=140, null=True, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='UsLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressLine1', models.CharField(max_length=45, verbose_name='Address line 1')),
                ('addressLine2', models.CharField(blank=True, max_length=45, verbose_name='address line 2')),
                ('postalCode', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=40, verbose_name='State')),
                ('country', models.CharField(max_length=40, verbose_name='Country')),
            ],
        ),
        migrations.DeleteModel(
            name='PersonalInformation',
        ),
        migrations.RemoveField(
            model_name='predentalweekendsignup',
            name='email',
        ),
        migrations.RemoveField(
            model_name='predentalweekendsignup',
            name='emergencyContactPhone',
        ),
        migrations.RemoveField(
            model_name='predentalweekendsignup',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='predentalweekendsignup',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='predentalweekendsignup',
            name='mailingAddress',
        ),
        migrations.AlterField(
            model_name='predentalweekendsignup',
            name='emergencyContactName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergencyContactName', to='forms.ContactInformation'),
        ),
        migrations.AddField(
            model_name='predentalweekendsignup',
            name='applicantContactInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicantContactInfo', to='forms.ContactInformation'),
        ),
    ]
