# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20161117_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predentalweekendsignup',
            old_name='emergencyContactName',
            new_name='emergencyContactInfo',
        ),
    ]
