# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Request', 'verbose_name_plural': 'Contact Requests'},
        ),
    ]
