# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20170206_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreDentalSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('Phone', models.CharField(max_length=30)),
                ('Address1', models.CharField(max_length=140)),
                ('Address2', models.CharField(max_length=140)),
                ('Email', models.CharField(max_length=70)),
                ('Gender', models.CharField(max_length=20)),
                ('School', models.CharField(max_length=140)),
                ('Year', models.CharField(max_length=140)),
                ('EmergName', models.CharField(max_length=140)),
                ('EmergPhone', models.CharField(max_length=30)),
                ('EmergEmail', models.CharField(max_length=70)),
                ('SocialEvent', models.CharField(max_length=10)),
                ('DietaryNeeds', models.CharField(max_length=200)),
                ('NeedHotel', models.BooleanField(default=False)),
            ],
        ),
    ]
