# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='headerImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
