# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_headerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='blogPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='blog.BlogPost'),
        ),
    ]
