# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20161218_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='blogPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost'),
        ),
    ]
