# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20161218_0503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='BlogImage',
        ),
    ]
