# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20161218_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='headerImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
