# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 02:05
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170112_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Options: LegislativeCommittee ||| Conferences ||| Advocacy ||| BookClub ||| CommunityService ||| HealthAndWellness ||| Fundraising ||| ', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
