# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 19:52
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_pay_pal_migrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Options: evo ||| x ||| 2015 ||| modified ||| Evo ||| LunchClub ||| Lunch ||| BookClub ||| lunch ||| lunchclub ||| HealthAndWellness ||| Conferences ||| CommunityService ||| Fundraising ||| LegislativeCommittee ||| Advocacy ||| Pediatrics ||| Social ||| Sustainability ||| ', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
